name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install cmake & libgtest-dev
      run: sudo apt-get install cmake libgtest-dev 
    - name: build gtest
      working-directory: /usr/src/gtest/
      run: |
        sudo cmake .
        sudo make
        sudo cp *.a /usr/lib
    - name: build project
      working-directory: /home/runner/work/cpp-project-template/cpp-project-template/
      run: |
        sudo cmake .
        sudo make
    - name: run tests
      working-directory: /home/runner/work/cpp-project-template/cpp-project-template/bin
      run: ./runTests
